export const certificateData = [
    {
        id: 1,
        title: "Belajar Membuat Aplikasi Web dengan React",
        issuer: "Dicoding Indonesia",
        issuerLogo: "logos:react",
        date: "2024",
        credentialUrl: "https://www.dicoding.com/certificates/",
        category: "Frontend",
        skills: ["React", "JSX", "Hooks", "SPA"],
        color: "#61DAFB",
    },
    {
        id: 2,
        title: "Belajar Dasar Pemrograman Web",
        issuer: "Dicoding Indonesia",
        issuerLogo: "devicon:html5",
        date: "2023",
        credentialUrl: "https://www.dicoding.com/certificates/",
        category: "Frontend",
        skills: ["HTML5", "CSS3", "JavaScript"],
        color: "#E34F26",
    },
    {
        id: 3,
        title: "Belajar Back-End Pemula dengan JavaScript",
        issuer: "Dicoding Indonesia",
        issuerLogo: "devicon:nodejs",
        date: "2024",
        credentialUrl: "https://www.dicoding.com/certificates/",
        category: "Backend",
        skills: ["Node.js", "Hapi.js", "REST API"],
        color: "#339933",
    },
    {
        id: 4,
        title: "Cloud Practitioner Essentials",
        issuer: "Dicoding Indonesia",
        issuerLogo: "logos:aws",
        date: "2024",
        credentialUrl: "https://www.dicoding.com/certificates/",
        category: "Cloud",
        skills: ["AWS", "Cloud Computing", "S3", "EC2"],
        color: "#FF9900",
    },
    {
        id: 5,
        title: "Belajar Dasar Git dengan GitHub",
        issuer: "Dicoding Indonesia",
        issuerLogo: "devicon:github",
        date: "2023",
        credentialUrl: "https://www.dicoding.com/certificates/",
        category: "Tools",
        skills: ["Git", "GitHub", "Version Control"],
        color: "#F05032",
    },
    {
        id: 6,
        title: "Pengenalan ke Logika Pemrograman",
        issuer: "Dicoding Indonesia",
        issuerLogo: "solar:code-bold",
        date: "2023",
        credentialUrl: "https://www.dicoding.com/certificates/",
        category: "Fundamental",
        skills: ["Algorithms", "Logic", "Problem Solving"],
        color: "#A78BFA",
    },
];
